version: '3.8'
services:
  myapp-main:
    image: golf_reg_api:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/golf_db_2025
      #- spring.datasource.url=jdbc:mysql://s4-fall-2022.ce2ycezhro2.us-east=1.rds.amazonaws.com/fall_2022
      - spring.datasource.password=HockeyVincent44!
      - spring.datasource.username=root

