version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: golf_mysql
    restart: always
    environment:
      MYSQL_DATABASE: golf_club
      MYSQL_USER: root
      MYSQL_PASSWORD: HockeyVincent44!
      MYSQL_ROOT_PASSWORD: HockeyVincent44!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  spring-app:
    build: .
    container_name: golf_backend
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/golf_club
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: HockeyVincent44!
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
